name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: setup nuget.exe
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-api-key: ${{ secrets.MYGETTOKEN }}
          nuget-version: '5.x'
      
      - name: build
        shell: pwsh
        run: |
          cd build
          .\build.ps1
          nuget pack build-for-myget.nuspec
          $nupkgName = @(gci *.nupkg)[0].Name
          $mygetSourcePath = "https://www.myget.org/F/handycontrol"
          nuget push $nupkgName -Source $mygetSourcePath
