name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: setup nuget.exe
        uses: NuGet/setup-nuget@master
      
      - name: build
        shell: pwsh
        run: |
          cd build
          .\build.ps1
          nuget pack build build-for-myget.nuspec
          $nupkgName = @(gci *.nupkg)[0].Name
          $mygetSourcePath = "https://www.myget.org/F/handycontrol"
          nuget setApiKey ${{ secrets.MYGETTOKEN }} -Source $mygetSourcePath
          nuget push $nupkgName -Source $mygetSourcePath
